import { createContext, useContext, useEffect, useState } from 'react'

const LanguageContext = createContext(null)

export const languages = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'ro', label: 'Română', flag: '🇷🇴' },
  { code: 'hu', label: 'Magyar', flag: '🇭🇺' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
]

export const translations = {
  en: {
    language: { label: 'Language', select: 'Select language' },
    nav: ['Home', 'About', 'Experience', 'Skills', 'Projects', 'Certifications', 'Contact'],
    navbar: { talk: "Let's Talk", menu: 'Toggle menu' },
    hero: {
      roles: ['Software Engineer', 'Full Stack Developer', 'Frontend Engineer', 'React & Node.js Developer', 'E-commerce Developer'],
      availability: 'Open to new opportunities', greeting: "Hi, I'm", scroll: 'Scroll',
      tagline: 'CS & Electrical Engineering graduate from Transilvania University, Brașov. I build maintainable full-stack applications, responsive interfaces, and e-commerce systems with a focus on performance, data, and practical user workflows.',
      contact: 'Get in Touch', work: 'View My Work',
    },
    about: {
      eyebrow: 'Who I am', title: 'About Me', available: 'Open to work',
      paragraphs: ['Computer Science and Electrical Engineering graduate from Transilvania University of Brașov, Romania. Over the course of five years across three companies, I have evolved into a versatile full-stack developer with experience delivering e-commerce platforms, internal tools, and performance-focused web applications.', 'My work spans custom Shopify Liquid storefronts, WordPress platforms, and full-stack applications built with React, TypeScript, Node.js, Express, Supabase & Vercel. I enjoy turning product requirements into robust interfaces, APIs, data flows, and measurable user outcomes while keeping performance and maintainability in view.'],
      pills: ['Brașov, Romania', 'CS & Electrical Engineering', '4 Languages'], languages: 'Languages',
      languageLevels: [['Hungarian', 'Native'], ['Romanian', 'Native'], ['English', 'B2 Advanced'], ['German', 'Basic']],
      stats: [['5+', 'Years Experience'], ['3', 'Companies'], ['15+', 'Technologies']],
    },
    experience: {
      eyebrow: 'Career Path', title: 'Work Experience', fullTime: 'Full-time',
      items: [
        { role: 'Web Developer & Digital Growth Specialist', duration: 'Jun 2025 — Present', summary: 'Spearheaded Ambisun’s digital transformation by delivering a stronger online presence, operational tools, and performance-focused web experiences for the premium pergola and glass systems market.', achievements: ['Executed a full website redesign covering information architecture, copy, and UX aligned with brand and conversion goals', 'Engineered custom contact and lead-generation forms that supported new client acquisition', 'Improved Core Web Vitals through script separation, conditional loading, and asset optimisation', 'Developed bespoke WordPress plugins for outlet and internal business workflows', 'Designed and deployed a full-stack internal analytics application with React, Vite, Supabase, and Vercel to track sales and operations', 'Modelled operational data and built reporting workflows for reliable product and sales performance insights', 'Worked across technical, marketing, and production teams to translate business requirements into usable solutions'] },
        { role: 'Frontend Web Developer', duration: 'Sep 2022 — Apr 2025', summary: 'Contributed to client-facing e-commerce and web projects with a focus on Shopify Liquid theme development, frontend performance, and polished, conversion-oriented interfaces.', achievements: ['Built and customised Shopify Liquid themes and e-commerce storefronts for client requirements', 'Delivered responsive, accessible interfaces using HTML5, CSS3, and Bootstrap', 'Implemented interactive frontend features and dynamic UI components with JavaScript and jQuery', 'Integrated third-party services and APIs using JSON-based data interchange', 'Managed source code and collaborative workflows via Git', 'Developed and maintained WordPress sites, broadening full-stack delivery capability'] },
        { role: 'Junior Web Developer', duration: '2020 — 2022', summary: 'Built foundational experience across frontend and backend development on client projects while developing core engineering discipline.', achievements: ['Developed and maintained client websites across frontend and backend layers', 'Designed and managed relational databases using PHP and MySQL', 'Applied C and C++ in systems-level and embedded contexts'] },
      ],
    },
    skills: { eyebrow: 'What I work with', title: 'Skills & Technologies', categories: ['Frontend', 'Shopify & E-commerce', 'Backend & Data', 'Engineering Tools', 'E-commerce & CMS', 'Application Delivery'] },
    projects: {
      eyebrow: "What I've built", title: 'Projects', live: 'Live', demo: 'Live Demo', source: 'Source Code', features: 'Key Features',
      items: [
        { subtitle: 'Full-Stack Business Intelligence Dashboard', description: 'A custom internal analytics platform built end-to-end for Ambisun, replacing manual spreadsheet tracking with a real-time business intelligence suite. The app centralises order management, product performance data, and sales analytics, giving the team a single source of truth for operational decisions.', features: ['KPI dashboard: total orders, products sold, and period-over-period trends', 'Order timeline and product performance charts with date range filtering', 'Product mix breakdown across pergola, glass, carport, and screen systems', 'Calendar view, order management, and analytics pages'] },
        { subtitle: 'EV Intelligence Platform & Range Calculator', description: 'A performance-focused TypeScript application for exploring a curated EV database. The latest version covers 149 electric vehicles across 52 brands, with fast filtering, detailed specifications, comparison workflows, and engineering tools for realistic range and charging planning.', features: ['149 EVs across 52 brands, with detailed specifications and model variants', 'Filter and browse the EV catalogue by brand, body style, range, price, and battery capacity', 'Compare up to three vehicles across range, efficiency, battery, and pricing data', 'Model real-world range, energy use, and charging stops with the Range Calculator and Engineering Lab'] },
      ],
    },
    certifications: { eyebrow: 'Achievements', title: 'Certifications & Education', links: ['View Credly Badge', 'View Certificate'], items: [['Networking Essentials', 'Fundamentals of networking, device communication, network addressing, and essential services.'], ['B2 Certificate in Advanced English', 'Upper-intermediate B2 English proficiency certified by Cambridge.'], ['Front-End Development', 'Full front-end curriculum: HTML, CSS, Bootstrap, JavaScript. Back-end module: PHP & MySQL.'], ["Bachelor’s Degree Project — eVerse", 'Full-stack e-learning platform developed as a Bachelor’s thesis: an online environment for future electrical engineers with curriculum delivery, user management, and interactive content.']] },
    contact: { eyebrow: 'Get in touch', title: 'Contact Me', intro: "Have a project, an idea, or an opportunity? I'd love to hear from you — whether it's a quick question or a detailed brief.", name: 'Your Name', email: 'Email Address', message: 'Message', namePlaceholder: 'John Doe', emailPlaceholder: 'john@example.com', messagePlaceholder: 'Tell me about your project or opportunity...', send: 'Send Message', sending: 'Opening your email client…', direct: 'Reach me directly', note: "I'm available for software engineering, frontend, and full-stack projects involving web applications, e-commerce systems, APIs, and internal tools.", details: ['Email', 'LinkedIn'] },
    footer: { description: 'Software engineer based in Brașov, Romania. Building reliable web applications, e-commerce systems, and data-driven tools.', quick: 'Quick Links', follow: 'Follow Me', made: 'Made with', by: 'by Szakacs Barna', built: 'Built with React · Vite · Tailwind CSS · Framer Motion' },
  },
  ro: {
    language: { label: 'Limbă', select: 'Selectează limba' },
    nav: ['Acasă', 'Despre', 'Experiență', 'Competențe', 'Proiecte', 'Certificări', 'Contact'], navbar: { talk: 'Hai să vorbim', menu: 'Comută meniul' },
    hero: { roles: ['Inginer software', 'Dezvoltator full-stack', 'Inginer frontend', 'Dezvoltator React și Node.js', 'Dezvoltator e-commerce'], availability: 'Deschis pentru noi oportunități', greeting: 'Salut, sunt', scroll: 'Derulează', tagline: 'Absolvent de Informatică și Inginerie Electrică la Universitatea Transilvania din Brașov. Construiesc aplicații full-stack ușor de întreținut, interfețe responsive și sisteme e-commerce, cu accent pe performanță, date și fluxuri de lucru utile.', contact: 'Contactează-mă', work: 'Vezi proiectele' },
    about: { eyebrow: 'Cine sunt', title: 'Despre mine', available: 'Disponibil pentru lucru', paragraphs: ['Absolvent de Informatică și Inginerie Electrică la Universitatea Transilvania din Brașov, România. În cinci ani, în cadrul a trei companii, am devenit un dezvoltator full-stack versatil, cu experiență în platforme e-commerce, instrumente interne și aplicații web orientate spre performanță.', 'Lucrez cu magazine Shopify Liquid personalizate, platforme WordPress și aplicații full-stack construite cu React, TypeScript, Node.js, Express, Supabase și Vercel. Îmi place să transform cerințele de produs în interfețe robuste, API-uri, fluxuri de date și rezultate măsurabile, păstrând performanța și mentenabilitatea în atenție.'], pills: ['Brașov, România', 'Informatică și Inginerie Electrică', '4 limbi'], languages: 'Limbi', languageLevels: [['Maghiară', 'Nativ'], ['Română', 'Nativ'], ['Engleză', 'B2 avansat'], ['Germană', 'Începător']], stats: [['5+', 'Ani de experiență'], ['3', 'Companii'], ['15+', 'Tehnologii']] },
    experience: { eyebrow: 'Parcurs profesional', title: 'Experiență profesională', fullTime: 'Normă întreagă', items: [{ role: 'Dezvoltator web și specialist în creștere digitală', duration: 'iun. 2025 — prezent', summary: 'Am coordonat transformarea digitală Ambisun prin livrarea unei prezențe online mai puternice, a unor instrumente operaționale și experiențe web performante pentru piața sistemelor premium de pergole și sticlă.', achievements: ['Am realizat redesignul complet al site-ului, incluzând arhitectura informației, conținutul și UX-ul, aliniate cu obiectivele de conversie', 'Am construit formulare personalizate de contact și generare de lead-uri care au susținut atragerea de clienți noi', 'Am îmbunătățit Core Web Vitals prin separarea scripturilor, încărcare condiționată și optimizarea resurselor', 'Am dezvoltat pluginuri WordPress pentru fluxuri de lucru interne și de outlet', 'Am proiectat și implementat o aplicație internă full-stack de analiză cu React, Vite, Supabase și Vercel pentru urmărirea vânzărilor și operațiunilor', 'Am modelat date operaționale și am construit fluxuri de raportare pentru informații fiabile despre produse și vânzări', 'Am colaborat cu echipe tehnice, de marketing și producție pentru a transforma cerințele de business în soluții utilizabile'] }, { role: 'Dezvoltator web frontend', duration: 'sept. 2022 — apr. 2025', summary: 'Am contribuit la proiecte web și e-commerce pentru clienți, cu accent pe dezvoltarea temelor Shopify Liquid, performanța frontend și interfețe finisate, orientate spre conversie.', achievements: ['Am construit și personalizat teme Shopify Liquid și magazine e-commerce pentru cerințele clienților', 'Am livrat interfețe responsive și accesibile folosind HTML5, CSS3 și Bootstrap', 'Am implementat funcționalități interactive și componente UI dinamice cu JavaScript și jQuery', 'Am integrat servicii terțe și API-uri prin schimb de date JSON', 'Am gestionat codul sursă și fluxurile colaborative cu Git', 'Am dezvoltat și întreținut site-uri WordPress, extinzând experiența full-stack'] }, { role: 'Dezvoltator web junior', duration: '2020 — 2022', summary: 'Am dobândit experiență de bază în dezvoltare frontend și backend pe proiecte pentru clienți, dezvoltând disciplină inginerească.', achievements: ['Am dezvoltat și întreținut site-uri pentru clienți pe straturile frontend și backend', 'Am proiectat și gestionat baze de date relaționale cu PHP și MySQL', 'Am aplicat C și C++ în contexte de sistem și embedded'] }] },
    skills: { eyebrow: 'Tehnologii utilizate', title: 'Competențe și tehnologii', categories: ['Frontend', 'Shopify și e-commerce', 'Backend și date', 'Instrumente de inginerie', 'E-commerce și CMS', 'Livrare aplicații'] },
    projects: { eyebrow: 'Ce am construit', title: 'Proiecte', live: 'Activ', demo: 'Demonstrație live', source: 'Cod sursă', features: 'Funcționalități cheie', items: [{ subtitle: 'Tablou de bord full-stack pentru business intelligence', description: 'O platformă internă de analiză construită cap-coadă pentru Ambisun, care înlocuiește urmărirea manuală în foi de calcul cu o suită de business intelligence în timp real. Aplicația centralizează gestionarea comenzilor, datele despre performanța produselor și analizele de vânzări, oferind echipei o singură sursă de adevăr pentru decizii operaționale.', features: ['Tablou KPI: comenzi totale, produse vândute și tendințe între perioade', 'Cronologie de comenzi și grafice de performanță a produselor cu filtrare după interval de date', 'Structura produselor pentru sisteme de pergole, sticlă, carport și screen', 'Calendar, gestionare comenzi și pagini de analiză'] }, { subtitle: 'Platformă de inteligență EV și calculator de autonomie', description: 'O aplicație TypeScript orientată spre performanță pentru explorarea unei baze de date EV curate. Cea mai nouă versiune acoperă 149 de vehicule electrice din 52 de mărci, cu filtrare rapidă, specificații detaliate, comparații și instrumente inginerești pentru planificarea autonomiei și încărcării.', features: ['149 de vehicule electrice din 52 de mărci, cu specificații detaliate și variante de model', 'Filtrare și navigare în catalog după marcă, caroserie, autonomie, preț și capacitatea bateriei', 'Compară până la trei vehicule după autonomie, eficiență, baterie și preț', 'Modelează autonomia reală, consumul de energie și opririle de încărcare cu Calculatorul și Engineering Lab'] }] },
    certifications: { eyebrow: 'Realizări', title: 'Certificări și educație', links: ['Vezi insigna Credly', 'Vezi certificatul'], items: [['Noțiuni esențiale de rețelistică', 'Fundamente de rețelistică, comunicarea dispozitivelor, adresarea rețelei și servicii esențiale.'], ['Certificat B2 de engleză avansată', 'Competență de limba engleză la nivel B2, certificată de Cambridge.'], ['Dezvoltare front-end', 'Curriculum complet de frontend: HTML, CSS, Bootstrap, JavaScript. Modul backend: PHP și MySQL.'], ['Proiect de licență — eVerse', 'Platformă full-stack de e-learning dezvoltată ca lucrare de licență: mediu online pentru viitori ingineri electricieni, cu curriculum, gestionarea utilizatorilor și conținut interactiv.']] },
    contact: { eyebrow: 'Ia legătura', title: 'Contactează-mă', intro: 'Ai un proiect, o idee sau o oportunitate? Mi-ar plăcea să discutăm, fie că este o întrebare rapidă sau un brief detaliat.', name: 'Numele tău', email: 'Adresa de e-mail', message: 'Mesaj', namePlaceholder: 'Ion Popescu', emailPlaceholder: 'ion@exemplu.ro', messagePlaceholder: 'Spune-mi despre proiectul sau oportunitatea ta...', send: 'Trimite mesajul', sending: 'Se deschide clientul de e-mail…', direct: 'Contact direct', note: 'Sunt disponibil pentru proiecte de inginerie software, frontend și full-stack care implică aplicații web, sisteme e-commerce, API-uri și instrumente interne.', details: ['E-mail', 'LinkedIn'] },
    footer: { description: 'Inginer software din Brașov, România. Construiesc aplicații web fiabile, sisteme e-commerce și instrumente bazate pe date.', quick: 'Linkuri rapide', follow: 'Urmărește-mă', made: 'Creat cu', by: 'de Szakacs Barna', built: 'Construit cu React · Vite · Tailwind CSS · Framer Motion' },
  },
  hu: {
    language: { label: 'Nyelv', select: 'Válassz nyelvet' },
    nav: ['Kezdőlap', 'Rólam', 'Tapasztalat', 'Készségek', 'Projektek', 'Tanúsítványok', 'Kapcsolat'], navbar: { talk: 'Beszéljünk', menu: 'Menü váltása' },
    hero: { roles: ['Szoftvermérnök', 'Full-stack fejlesztő', 'Frontend mérnök', 'React és Node.js fejlesztő', 'E-kereskedelmi fejlesztő'], availability: 'Nyitott vagyok új lehetőségekre', greeting: 'Üdv, Barna vagyok', scroll: 'Görgess', tagline: 'A Brassói Transilvania Egyetem informatika és villamosmérnöki szakán végeztem. Karbantartható full-stack alkalmazásokat, reszponzív felületeket és e-kereskedelmi rendszereket építek, a teljesítményre, adatokra és gyakorlati munkafolyamatokra összpontosítva.', contact: 'Kapcsolat', work: 'Munkáim megtekintése' },
    about: { eyebrow: 'Rólam', title: 'Bemutatkozás', available: 'Munkára nyitott', paragraphs: ['A Brassói Transilvania Egyetem informatika és villamosmérnöki szakán végeztem Romániában. Három vállalatnál eltöltött öt év alatt sokoldalú full-stack fejlesztővé váltam, e-kereskedelmi platformok, belső eszközök és teljesítményorientált webalkalmazások szállításában szerzett tapasztalattal.', 'Munkám egyedi Shopify Liquid áruházakat, WordPress platformokat és React, TypeScript, Node.js, Express, Supabase és Vercel alapú full-stack alkalmazásokat foglal magában. Szeretem a termékkövetelményeket robusztus felületekké, API-kká, adatfolyamokká és mérhető eredményekké alakítani, miközben figyelek a teljesítményre és a karbantarthatóságra.'], pills: ['Brassó, Románia', 'Informatika és villamosmérnöki', '4 nyelv'], languages: 'Nyelvek', languageLevels: [['Magyar', 'Anyanyelvi'], ['Román', 'Anyanyelvi'], ['Angol', 'B2 haladó'], ['Német', 'Alapfok']], stats: [['5+', 'Év tapasztalat'], ['3', 'Vállalat'], ['15+', 'Technológia']] },
    experience: { eyebrow: 'Szakmai út', title: 'Szakmai tapasztalat', fullTime: 'Teljes munkaidő', items: [{ role: 'Webfejlesztő és digitális növekedési szakértő', duration: '2025. jún. — jelenleg', summary: 'Az Ambisun digitális átalakulását vezettem erősebb online jelenlét, operatív eszközök és teljesítményorientált webes élmények megvalósításával a prémium pergola- és üvegrendszerek piacán.', achievements: ['Teljes weboldal-újratervezést valósítottam meg, beleértve az információs architektúrát, a szöveget és az UX-et, a márka- és konverziós célokhoz igazítva', 'Egyedi kapcsolatfelvételi és leadgeneráló űrlapokat fejlesztettem, amelyek új ügyfelek szerzését támogatták', 'A Core Web Vitals értékeket szkriptek szétválasztásával, feltételes betöltéssel és eszközoptimalizálással javítottam', 'Egyedi WordPress bővítményeket fejlesztettem belső és outlet munkafolyamatokhoz', 'React, Vite, Supabase és Vercel használatával teljes körű belső analitikai alkalmazást terveztem és telepítettem az értékesítés és működés követésére', 'Operatív adatokat modelleztem és jelentési munkafolyamatokat építettem megbízható termék- és értékesítési betekintésekhez', 'Műszaki, marketing- és gyártási csapatokkal dolgoztam együtt az üzleti igények használható megoldásokká alakításán'] }, { role: 'Frontend webfejlesztő', duration: '2022. szept. — 2025. ápr.', summary: 'Ügyfélközpontú e-kereskedelmi és webes projektekhez járultam hozzá, elsősorban Shopify Liquid témafejlesztésre, frontend teljesítményre és kifinomult, konverzióorientált felületekre összpontosítva.', achievements: ['Shopify Liquid témákat és e-kereskedelmi áruházakat építettem és testreszabtam ügyféligényekhez', 'Reszponzív, akadálymentes felületeket készítettem HTML5, CSS3 és Bootstrap használatával', 'Interaktív frontend funkciókat és dinamikus UI-komponenseket valósítottam meg JavaScript és jQuery segítségével', 'Harmadik féltől származó szolgáltatásokat és API-kat integráltam JSON alapú adatcserével', 'Git segítségével kezeltem a forráskódot és az együttműködési munkafolyamatokat', 'WordPress oldalakat fejlesztettem és tartottam karban, bővítve full-stack tapasztalatomat'] }, { role: 'Junior webfejlesztő', duration: '2020 — 2022', summary: 'Frontend és backend fejlesztési alapismereteket szereztem ügyfélprojekteken, miközben kiépítettem a mérnöki munkához szükséges fegyelmet.', achievements: ['Ügyfélweboldalakat fejlesztettem és tartottam karban frontend és backend rétegekben', 'Relációs adatbázisokat terveztem és kezeltem PHP és MySQL használatával', 'C és C++ nyelveket alkalmaztam rendszer- és beágyazott környezetekben'] }] },
    skills: { eyebrow: 'Amivel dolgozom', title: 'Készségek és technológiák', categories: ['Frontend', 'Shopify és e-kereskedelem', 'Backend és adatok', 'Mérnöki eszközök', 'E-kereskedelem és CMS', 'Alkalmazásszállítás'] },
    projects: { eyebrow: 'Amit építettem', title: 'Projektek', live: 'Élő', demo: 'Élő bemutató', source: 'Forráskód', features: 'Fő funkciók', items: [{ subtitle: 'Full-stack üzletiintelligencia-irányítópult', description: 'Az Ambisun számára végponttól végpontig épített belső analitikai platform, amely a manuális táblázatkezelést valós idejű üzletiintelligencia-rendszerrel váltja fel. Az alkalmazás központosítja a rendeléskezelést, a termékteljesítmény-adatokat és az értékesítési elemzéseket, egységes forrást adva az operatív döntésekhez.', features: ['KPI irányítópult: összes rendelés, eladott termékek és időszakok közötti trendek', 'Rendelési idővonal és termékteljesítmény-grafikonok dátumtartomány szerinti szűréssel', 'Termékmix bontása pergola-, üveg-, carport- és screen rendszereknél', 'Naptárnézet, rendeléskezelő és analitikai oldalak'] }, { subtitle: 'EV intelligenciaplatform és hatótávkalkulátor', description: 'Teljesítményközpontú TypeScript alkalmazás egy gondozott elektromosjármű-adatbázis felfedezéséhez. A legújabb verzió 52 márka 149 elektromos járművét tartalmazza gyors szűréssel, részletes specifikációkkal, összehasonlításokkal, valamint a valós hatótáv és töltés tervezését támogató mérnöki eszközökkel.', features: ['149 elektromos jármű 52 márkától, részletes specifikációkkal és modellváltozatokkal', 'EV katalógus szűrése és böngészése márka, karosszéria, hatótáv, ár és akkumulátorkapacitás szerint', 'Legfeljebb három jármű összehasonlítása hatótáv, hatékonyság, akkumulátor és ár alapján', 'Valós hatótáv, energiafelhasználás és töltési megállók modellezése a kalkulátorral és az Engineering Labbal'] }] },
    certifications: { eyebrow: 'Eredmények', title: 'Tanúsítványok és képzés', links: ['Credly jelvény megtekintése', 'Tanúsítvány megtekintése'], items: [['Hálózati alapismeretek', 'A hálózatok, eszközkommunikáció, hálózati címzés és alapvető szolgáltatások alapjai.'], ['B2 szintű haladó angol nyelvvizsga', 'Cambridge által tanúsított B2 szintű angol nyelvtudás.'], ['Frontend fejlesztés', 'Teljes frontend tananyag: HTML, CSS, Bootstrap, JavaScript. Backend modul: PHP és MySQL.'], ['Szakdolgozati projekt — eVerse', 'Szakdolgozatként fejlesztett full-stack e-learning platform: online környezet jövőbeli villamosmérnökök számára tananyaggal, felhasználókezeléssel és interaktív tartalommal.']] },
    contact: { eyebrow: 'Kapcsolat', title: 'Lépj kapcsolatba velem', intro: 'Van egy projekted, ötleted vagy lehetőséged? Szívesen hallok róla, legyen szó gyors kérdésről vagy részletes leírásról.', name: 'Neved', email: 'E-mail-cím', message: 'Üzenet', namePlaceholder: 'Kovács János', emailPlaceholder: 'janos@pelda.hu', messagePlaceholder: 'Írj a projektedről vagy lehetőségről...', send: 'Üzenet küldése', sending: 'Az e-mail-kliens megnyitása…', direct: 'Közvetlen kapcsolat', note: 'Szoftvermérnöki, frontend és full-stack projekteket vállalok, webalkalmazásokkal, e-kereskedelmi rendszerekkel, API-kkal és belső eszközökkel kapcsolatban.', details: ['E-mail', 'LinkedIn'] },
    footer: { description: 'Brassói szoftvermérnök. Megbízható webalkalmazásokat, e-kereskedelmi rendszereket és adatalapú eszközöket építek.', quick: 'Gyorslinkek', follow: 'Kövess', made: 'Készítette', by: 'Szakacs Barna', built: 'React · Vite · Tailwind CSS · Framer Motion felhasználásával készült' },
  },
  de: {
    language: { label: 'Sprache', select: 'Sprache auswählen' },
    nav: ['Startseite', 'Über mich', 'Erfahrung', 'Kompetenzen', 'Projekte', 'Zertifikate', 'Kontakt'], navbar: { talk: 'Kontakt aufnehmen', menu: 'Menü umschalten' },
    hero: { roles: ['Softwareingenieur', 'Full-Stack-Entwickler', 'Frontend-Ingenieur', 'React- und Node.js-Entwickler', 'E-Commerce-Entwickler'], availability: 'Offen für neue Möglichkeiten', greeting: 'Hallo, ich bin', scroll: 'Scrollen', tagline: 'Absolvent der Informatik und Elektrotechnik an der Transilvania-Universität Brașov. Ich entwickle wartbare Full-Stack-Anwendungen, responsive Oberflächen und E-Commerce-Systeme mit Fokus auf Performance, Daten und praktische Arbeitsabläufe.', contact: 'Kontakt aufnehmen', work: 'Meine Arbeit ansehen' },
    about: { eyebrow: 'Über mich', title: 'Über mich', available: 'Offen für Arbeit', paragraphs: ['Absolvent der Informatik und Elektrotechnik an der Transilvania-Universität Brașov, Rumänien. In fünf Jahren bei drei Unternehmen entwickelte ich mich zu einem vielseitigen Full-Stack-Entwickler mit Erfahrung in E-Commerce-Plattformen, internen Tools und leistungsorientierten Webanwendungen.', 'Meine Arbeit umfasst individuelle Shopify-Liquid-Shops, WordPress-Plattformen und Full-Stack-Anwendungen mit React, TypeScript, Node.js, Express, Supabase und Vercel. Ich setze Produktanforderungen gerne in robuste Oberflächen, APIs, Datenflüsse und messbare Ergebnisse um und behalte dabei Performance und Wartbarkeit im Blick.'], pills: ['Brașov, Rumänien', 'Informatik und Elektrotechnik', '4 Sprachen'], languages: 'Sprachen', languageLevels: [['Ungarisch', 'Muttersprache'], ['Rumänisch', 'Muttersprache'], ['Englisch', 'B2 Fortgeschritten'], ['Deutsch', 'Grundkenntnisse']], stats: [['5+', 'Jahre Erfahrung'], ['3', 'Unternehmen'], ['15+', 'Technologien']] },
    experience: { eyebrow: 'Beruflicher Werdegang', title: 'Berufserfahrung', fullTime: 'Vollzeit', items: [{ role: 'Webentwickler und Spezialist für digitales Wachstum', duration: 'Juni 2025 — heute', summary: 'Ich leitete die digitale Transformation von Ambisun durch eine stärkere Online-Präsenz, operative Tools und leistungsorientierte Web-Erlebnisse für den Markt hochwertiger Pergola- und Glassysteme.', achievements: ['Kompletten Website-Relaunch inklusive Informationsarchitektur, Texten und UX umgesetzt, abgestimmt auf Marken- und Conversion-Ziele', 'Individuelle Kontakt- und Leadgenerierungsformulare entwickelt, die die Gewinnung neuer Kunden unterstützten', 'Core Web Vitals durch Skripttrennung, bedingtes Laden und Asset-Optimierung verbessert', 'Individuelle WordPress-Plugins für Outlet- und interne Geschäftsprozesse entwickelt', 'Eine interne Full-Stack-Analyseanwendung mit React, Vite, Supabase und Vercel zur Verfolgung von Umsatz und Betrieb entwickelt und bereitgestellt', 'Betriebsdaten modelliert und Reporting-Workflows für verlässliche Einblicke in Produkt- und Vertriebsleistung aufgebaut', 'Mit Technik-, Marketing- und Produktionsteams zusammengearbeitet, um Geschäftsanforderungen in nutzbare Lösungen zu übersetzen'] }, { role: 'Frontend-Webentwickler', duration: 'Sept. 2022 — Apr. 2025', summary: 'Ich arbeitete an kundenorientierten E-Commerce- und Webprojekten mit Schwerpunkt auf Shopify-Liquid-Theme-Entwicklung, Frontend-Performance und ausgearbeiteten, conversion-orientierten Oberflächen.', achievements: ['Shopify-Liquid-Themes und E-Commerce-Shops nach Kundenanforderungen entwickelt und angepasst', 'Responsive und barrierearme Oberflächen mit HTML5, CSS3 und Bootstrap geliefert', 'Interaktive Frontend-Funktionen und dynamische UI-Komponenten mit JavaScript und jQuery umgesetzt', 'Drittanbieter-Dienste und APIs über JSON-basierten Datenaustausch integriert', 'Quellcode und kollaborative Arbeitsabläufe mit Git verwaltet', 'WordPress-Websites entwickelt und gepflegt, wodurch sich die Full-Stack-Erfahrung erweiterte'] }, { role: 'Junior-Webentwickler', duration: '2020 — 2022', summary: 'Grundlegende Erfahrung in Frontend- und Backend-Entwicklung auf Kundenprojekten gesammelt und dabei technische Disziplin aufgebaut.', achievements: ['Kundenwebsites in Frontend- und Backend-Schichten entwickelt und gepflegt', 'Relationale Datenbanken mit PHP und MySQL entworfen und verwaltet', 'C und C++ in systemnahen und Embedded-Kontexten eingesetzt'] }] },
    skills: { eyebrow: 'Womit ich arbeite', title: 'Kompetenzen und Technologien', categories: ['Frontend', 'Shopify und E-Commerce', 'Backend und Daten', 'Engineering-Werkzeuge', 'E-Commerce und CMS', 'Anwendungsbereitstellung'] },
    projects: { eyebrow: 'Was ich entwickelt habe', title: 'Projekte', live: 'Live', demo: 'Live-Demo', source: 'Quellcode', features: 'Kernfunktionen', items: [{ subtitle: 'Full-Stack-Business-Intelligence-Dashboard', description: 'Eine von Grund auf entwickelte interne Analyseplattform für Ambisun, die manuelle Tabellenverfolgung durch eine Business-Intelligence-Suite in Echtzeit ersetzt. Die Anwendung zentralisiert Auftragsverwaltung, Produktleistungsdaten und Vertriebsanalysen und bietet dem Team eine zentrale Grundlage für operative Entscheidungen.', features: ['KPI-Dashboard: Gesamtaufträge, verkaufte Produkte und Trends im Periodenvergleich', 'Auftragszeitleiste und Produktleistungsdiagramme mit Datumsbereichsfilterung', 'Produktmix-Aufschlüsselung für Pergola-, Glas-, Carport- und Screen-Systeme', 'Kalenderansicht, Auftragsverwaltung und Analyseseiten'] }, { subtitle: 'EV-Intelligenzplattform und Reichweitenrechner', description: 'Eine leistungsorientierte TypeScript-Anwendung zum Erkunden einer kuratierten EV-Datenbank. Die neueste Version umfasst 149 Elektrofahrzeuge von 52 Marken mit schneller Filterung, detaillierten Spezifikationen, Vergleichsabläufen und Engineering-Tools für realistische Reichweiten- und Ladeplanung.', features: ['149 Elektrofahrzeuge von 52 Marken mit detaillierten Spezifikationen und Modellvarianten', 'EV-Katalog nach Marke, Karosserieform, Reichweite, Preis und Batteriekapazität filtern und durchsuchen', 'Bis zu drei Fahrzeuge nach Reichweite, Effizienz, Batterie und Preisdaten vergleichen', 'Reale Reichweite, Energieverbrauch und Ladestopps mit Reichweitenrechner und Engineering Lab modellieren'] }] },
    certifications: { eyebrow: 'Erfolge', title: 'Zertifikate und Ausbildung', links: ['Credly-Abzeichen ansehen', 'Zertifikat ansehen'], items: [['Netzwerk-Grundlagen', 'Grundlagen von Netzwerken, Gerätekommunikation, Netzwerkadressierung und wesentlichen Diensten.'], ['B2-Zertifikat für fortgeschrittenes Englisch', 'Von Cambridge zertifizierte Englischkenntnisse auf B2-Niveau.'], ['Frontend-Entwicklung', 'Vollständiger Frontend-Lehrplan: HTML, CSS, Bootstrap, JavaScript. Backend-Modul: PHP und MySQL.'], ['Bachelorprojekt — eVerse', 'Als Bachelorarbeit entwickelte Full-Stack-E-Learning-Plattform: Online-Umgebung für künftige Elektroingenieure mit Lehrinhalten, Benutzerverwaltung und interaktiven Inhalten.']] },
    contact: { eyebrow: 'Kontakt', title: 'Kontaktieren Sie mich', intro: 'Haben Sie ein Projekt, eine Idee oder eine Gelegenheit? Ich freue mich, davon zu hören, egal ob es eine kurze Frage oder ein detailliertes Briefing ist.', name: 'Ihr Name', email: 'E-Mail-Adresse', message: 'Nachricht', namePlaceholder: 'Max Mustermann', emailPlaceholder: 'max@beispiel.de', messagePlaceholder: 'Erzählen Sie mir von Ihrem Projekt oder Ihrer Gelegenheit...', send: 'Nachricht senden', sending: 'E-Mail-Programm wird geöffnet…', direct: 'Direkter Kontakt', note: 'Ich bin für Software-Engineering-, Frontend- und Full-Stack-Projekte verfügbar, die Webanwendungen, E-Commerce-Systeme, APIs und interne Tools umfassen.', details: ['E-Mail', 'LinkedIn'] },
    footer: { description: 'Softwareingenieur aus Brașov, Rumänien. Ich entwickle zuverlässige Webanwendungen, E-Commerce-Systeme und datengestützte Tools.', quick: 'Schnelllinks', follow: 'Folgen Sie mir', made: 'Erstellt mit', by: 'von Szakacs Barna', built: 'Erstellt mit React · Vite · Tailwind CSS · Framer Motion' },
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('portfolio-language') || 'en')

  useEffect(() => {
    document.documentElement.lang = language
    localStorage.setItem('portfolio-language', language)
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}