import { createContext, useContext, useEffect, useState } from 'react'

const LanguageContext = createContext(null)

export const languages = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'ro', label: 'Română', flag: '🇷🇴' },
  { code: 'hu', label: 'Magyar', flag: '🇭🇺' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
]

export const translations = {
  en: {
    language: { label: 'Language', select: 'Select language' },
    nav: ['Home', 'About', 'Experience', 'Skills', 'Projects', 'Certifications', 'Contact'],
    navbar: { talk: "Let's Talk", menu: 'Toggle menu' },
    hero: {
      roles: ['Software Engineer', 'Full Stack Developer', 'Business Application Developer', 'React & Node.js Developer', 'Frontend Engineer'],
      availability: 'Open to new opportunities', greeting: "Hi, I'm", scroll: 'Scroll',
      tagline: 'CS & Electrical Engineering graduate from Transilvania University, Brașov. I build maintainable business applications, responsive interfaces, and operational tools with a focus on data, performance, and practical user workflows.',
      contact: 'Get in Touch', work: 'View My Work',
    },
    about: {
      eyebrow: 'Who I am', title: 'About Me', available: 'Open to work',
      paragraphs: ['Computer Science and Electrical Engineering graduate from Transilvania University of Brașov, Romania. Over five years across three companies, I have delivered e-commerce platforms, internal business tools, and performance-focused web applications.', 'My work includes a role-based internal operations platform with order, task, calendar, document-tracking, notification, and reporting workflows. I build with React, TypeScript, Node.js, Express, Supabase, and Vercel, translating product requirements into robust interfaces, APIs, data flows, and maintainable software.'],
      pills: ['Brașov, Romania', 'CS & Electrical Engineering', '4 Languages'], languages: 'Languages',
      languageLevels: [['Hungarian', 'Native'], ['Romanian', 'Native'], ['English', 'B2 Advanced'], ['German', 'Basic']],
      stats: [['5+', 'Years Experience'], ['3', 'Companies'], ['15+', 'Technologies']],
    },
    experience: {
      eyebrow: 'Career Path', title: 'Work Experience', fullTime: 'Full-time',
      items: [
        { role: 'Web Developer & Digital Growth Specialist', duration: 'Jun 2025 — Present', summary: 'Delivered Ambisun’s digital transformation through a stronger online presence, an internal operations platform, and performance-focused web experiences for the premium pergola and glass systems market.', achievements: ['Designed and deployed a role-based internal operations platform for staff and administrators using React, Vite, Supabase, and Vercel', 'Implemented database-backed workflows for editable orders, colour-coded tasks, calendars, rescheduling, and workflow management', 'Built document-tracking and notification flows for company vehicle records and operational follow-up', 'Delivered sales and completed-order analytics to support operational decisions and reporting', 'Improved Core Web Vitals through script separation, conditional loading, and asset optimisation', 'Moved key pergola searches from page six to local top-three and national top-five positions through technical and on-page SEO improvements', 'Worked across technical, marketing, production, and installation teams to translate operational requirements into usable tools'] },
        { role: 'Frontend Web Developer', duration: 'Sep 2022 — Apr 2025', summary: 'Contributed to client-facing e-commerce and web projects with a focus on Shopify Liquid theme development, frontend performance, and polished, conversion-oriented interfaces.', achievements: ['Built and customised Shopify Liquid themes and e-commerce storefronts for client requirements', 'Delivered responsive, accessible interfaces using HTML5, CSS3, and Bootstrap', 'Implemented interactive frontend features and dynamic UI components with JavaScript and jQuery', 'Integrated third-party services and APIs using JSON-based data interchange', 'Managed source code and collaborative workflows via Git', 'Developed and maintained WordPress sites, broadening full-stack delivery capability'] },
        { role: 'Junior Web Developer', duration: '2020 — 2022', summary: 'Built foundational experience across frontend and backend development on client projects while developing core engineering discipline.', achievements: ['Developed and maintained client websites across frontend and backend layers', 'Designed and managed relational databases using PHP and MySQL', 'Applied C and C++ in systems-level and embedded contexts'] },
      ],
    },
    skills: { eyebrow: 'What I work with', title: 'Skills & Technologies', categories: ['Frontend', 'Shopify & E-commerce', 'Backend & Data', 'Engineering Tools', 'E-commerce & CMS', 'Application Delivery'] },
    projects: {
      eyebrow: "What I've built", title: 'Projects', live: 'Live', demo: 'Live Demo', source: 'Source Code', features: 'Key Features',
      items: [
        { subtitle: 'Internal Operations & Business Intelligence Platform', description: 'A full-stack internal platform built end-to-end for Ambisun, replacing fragmented manual tracking with connected operational workflows. Role-based staff and administrator views support order management, tasks, calendars, document follow-up, notifications, and sales reporting in one system.', features: ['Role-based staff and administrator workflows for daily operations', 'Editable orders, colour-coded tasks, calendar scheduling, and rescheduling workflows', 'Vehicle document tracking with notifications for operational follow-up', 'KPI reporting for sales and completed orders, with product and order analysis'] },
        { subtitle: 'EV Intelligence Platform & Range Calculator', description: 'A performance-focused TypeScript application for exploring a curated EV database. The latest version covers 149 electric vehicles across 52 brands, with fast filtering, detailed specifications, comparison workflows, and engineering tools for realistic range and charging planning.', features: ['149 EVs across 52 brands, with detailed specifications and model variants', 'Filter and browse the EV catalogue by brand, body style, range, price, and battery capacity', 'Compare up to three vehicles across range, efficiency, battery, and pricing data', 'Model real-world range, energy use, and charging stops with the Range Calculator and Engineering Lab'] },
      ],
    },
    certifications: { eyebrow: 'Achievements', title: 'Certifications & Education', links: ['View Credly Badge', 'View Certificate'], items: [['Networking Essentials', 'Fundamentals of networking, device communication, network addressing, and essential services.'], ['B2 Certificate in Advanced English', 'Upper-intermediate B2 English proficiency certified by Cambridge.'], ['Front-End Development', 'Full front-end curriculum: HTML, CSS, Bootstrap, JavaScript. Back-end module: PHP & MySQL.'], ["Bachelor’s Degree Project — eVerse", 'Full-stack e-learning platform developed as a Bachelor’s thesis: an online environment for future electrical engineers with curriculum delivery, user management, and interactive content.']] },
    contact: { eyebrow: 'Get in touch', title: 'Contact Me', intro: "Have a project, an idea, or an opportunity? I'd love to hear from you — whether it's a quick question or a detailed brief.", name: 'Your Name', email: 'Email Address', message: 'Message', namePlaceholder: 'John Doe', emailPlaceholder: 'john@example.com', messagePlaceholder: 'Tell me about your project or opportunity...', send: 'Send Message', sending: 'Opening your email client…', direct: 'Reach me directly', note: "I'm available for software engineering, frontend, and full-stack projects involving web applications, e-commerce systems, APIs, and internal tools.", details: ['Email', 'LinkedIn'] },
    footer: { description: 'Software engineer based in Brașov, Romania. Building reliable web applications, e-commerce systems, and data-driven tools.', quick: 'Quick Links', follow: 'Follow Me', made: 'Made with', by: 'by Szakacs Barna', built: 'Built with React · Vite · Tailwind CSS · Framer Motion' },
  },
  ro: {
    language: { label: 'Limbă', select: 'Selectează limba' },
    nav: ['Acasă', 'Despre', 'Experiență', 'Competențe', 'Proiecte', 'Certificări', 'Contact'], navbar: { talk: 'Hai să vorbim', menu: 'Comută meniul' },
    hero: { roles: ['Inginer software', 'Dezvoltator full-stack', 'Dezvoltator aplicații business', 'Dezvoltator React și Node.js', 'Inginer frontend'], availability: 'Deschis pentru noi oportunități', greeting: 'Salut, sunt', scroll: 'Derulează', tagline: 'Absolvent de Informatică și Inginerie Electrică la Universitatea Transilvania din Brașov. Construiesc aplicații business ușor de întreținut, interfețe responsive și instrumente operaționale, cu accent pe date, performanță și fluxuri de lucru utile.', contact: 'Contactează-mă', work: 'Vezi proiectele' },
    about: { eyebrow: 'Cine sunt', title: 'Despre mine', available: 'Disponibil pentru lucru', paragraphs: ['Absolvent de Informatică și Inginerie Electrică la Universitatea Transilvania din Brașov, România. În cinci ani, în cadrul a trei companii, am livrat platforme e-commerce, instrumente interne de business și aplicații web orientate spre performanță.', 'Munca mea include o platformă internă de operațiuni cu roluri de utilizator, comenzi, taskuri, calendar, urmărirea documentelor, notificări și raportare. Construiesc cu React, TypeScript, Node.js, Express, Supabase și Vercel, transformând cerințele de produs în interfețe robuste, API-uri, fluxuri de date și software ușor de întreținut.'], pills: ['Brașov, România', 'Informatică și Inginerie Electrică', '4 limbi'], languages: 'Limbi', languageLevels: [['Maghiară', 'Nativ'], ['Română', 'Nativ'], ['Engleză', 'B2 avansat'], ['Germană', 'Începător']], stats: [['5+', 'Ani de experiență'], ['3', 'Companii'], ['15+', 'Tehnologii']] },
    experience: { eyebrow: 'Parcurs profesional', title: 'Experiență profesională', fullTime: 'Normă întreagă', items: [{ role: 'Dezvoltator web și specialist în creștere digitală', duration: 'iun. 2025 — prezent', summary: 'Am livrat transformarea digitală Ambisun printr-o prezență online mai puternică, o platformă internă de operațiuni și experiențe web performante pentru piața sistemelor premium de pergole și sticlă.', achievements: ['Am proiectat și implementat o platformă internă de operațiuni cu roluri pentru angajați și administratori, folosind React, Vite, Supabase și Vercel', 'Am implementat fluxuri bazate pe baze de date pentru comenzi editabile, taskuri colorate, calendare, reprogramări și management de workflow', 'Am construit urmărirea documentelor și fluxuri de notificări pentru evidența vehiculelor firmei și activități operaționale', 'Am livrat analize pentru vânzări și comenzi finalizate, pentru decizii operaționale și raportare', 'Am îmbunătățit Core Web Vitals prin separarea scripturilor, încărcare condiționată și optimizarea resurselor', 'Am mutat căutările importante pentru pergole de la pagina șase la poziții locale top trei și naționale top cinci prin îmbunătățiri SEO tehnice și on-page', 'Am colaborat cu echipe tehnice, de marketing, producție și montaj pentru a transforma cerințele operaționale în instrumente utilizabile'] }, { role: 'Dezvoltator web frontend', duration: 'sept. 2022 — apr. 2025', summary: 'Am contribuit la proiecte web și e-commerce pentru clienți, cu accent pe dezvoltarea temelor Shopify Liquid, performanța frontend și interfețe finisate, orientate spre conversie.', achievements: ['Am construit și personalizat teme Shopify Liquid și magazine e-commerce pentru cerințele clienților', 'Am livrat interfețe responsive și accesibile folosind HTML5, CSS3 și Bootstrap', 'Am implementat funcționalități interactive și componente UI dinamice cu JavaScript și jQuery', 'Am integrat servicii terțe și API-uri prin schimb de date JSON', 'Am gestionat codul sursă și fluxurile colaborative cu Git', 'Am dezvoltat și întreținut site-uri WordPress, extinzând experiența full-stack'] }, { role: 'Dezvoltator web junior', duration: '2020 — 2022', summary: 'Am dobândit experiență de bază în dezvoltare frontend și backend pe proiecte pentru clienți, dezvoltând disciplină inginerească.', achievements: ['Am dezvoltat și întreținut site-uri pentru clienți pe straturile frontend și backend', 'Am proiectat și gestionat baze de date relaționale cu PHP și MySQL', 'Am aplicat C și C++ în contexte de sistem și embedded'] }] },
    skills: { eyebrow: 'Tehnologii utilizate', title: 'Competențe și tehnologii', categories: ['Frontend', 'Shopify și e-commerce', 'Backend și date', 'Instrumente de inginerie', 'E-commerce și CMS', 'Livrare aplicații'] },
    projects: { eyebrow: 'Ce am construit', title: 'Proiecte', live: 'Activ', demo: 'Demonstrație live', source: 'Cod sursă', features: 'Funcționalități cheie', items: [{ subtitle: 'Platformă internă de operațiuni și business intelligence', description: 'O platformă internă full-stack construită cap-coadă pentru Ambisun, care înlocuiește urmărirea fragmentată cu fluxuri operaționale conectate. Vizualizările pentru angajați și administratori susțin gestionarea comenzilor, taskurilor, calendarelor, documentelor, notificărilor și raportării de vânzări într-un singur sistem.', features: ['Fluxuri pentru angajați și administratori pentru operațiunile zilnice', 'Comenzi editabile, taskuri colorate, programare în calendar și fluxuri de reprogramare', 'Urmărirea documentelor vehiculelor cu notificări pentru activități operaționale', 'Raportare KPI pentru vânzări și comenzi finalizate, cu analiză de produse și comenzi'] }, { subtitle: 'Platformă de inteligență EV și calculator de autonomie', description: 'O aplicație TypeScript orientată spre performanță pentru explorarea unei baze de date EV curate. Cea mai nouă versiune acoperă 149 de vehicule electrice din 52 de mărci, cu filtrare rapidă, specificații detaliate, comparații și instrumente inginerești pentru planificarea autonomiei și încărcării.', features: ['149 de vehicule electrice din 52 de mărci, cu specificații detaliate și variante de model', 'Filtrare și navigare în catalog după marcă, caroserie, autonomie, preț și capacitatea bateriei', 'Compară până la trei vehicule după autonomie, eficiență, baterie și preț', 'Modelează autonomia reală, consumul de energie și opririle de încărcare cu Calculatorul și Engineering Lab'] }] },
    certifications: { eyebrow: 'Realizări', title: 'Certificări și educație', links: ['Vezi insigna Credly', 'Vezi certificatul'], items: [['Noțiuni esențiale de rețelistică', 'Fundamente de rețelistică, comunicarea dispozitivelor, adresarea rețelei și servicii esențiale.'], ['Certificat B2 de engleză avansată', 'Competență de limba engleză la nivel B2, certificată de Cambridge.'], ['Dezvoltare front-end', 'Curriculum complet de frontend: HTML, CSS, Bootstrap, JavaScript. Modul backend: PHP și MySQL.'], ['Proiect de licență — eVerse', 'Platformă full-stack de e-learning dezvoltată ca lucrare de licență: mediu online pentru viitori ingineri electricieni, cu curriculum, gestionarea utilizatorilor și conținut interactiv.']] },
    contact: { eyebrow: 'Ia legătura', title: 'Contactează-mă', intro: 'Ai un proiect, o idee sau o oportunitate? Mi-ar plăcea să discutăm, fie că este o întrebare rapidă sau un brief detaliat.', name: 'Numele tău', email: 'Adresa de e-mail', message: 'Mesaj', namePlaceholder: 'Ion Popescu', emailPlaceholder: 'ion@exemplu.ro', messagePlaceholder: 'Spune-mi despre proiectul sau oportunitatea ta...', send: 'Trimite mesajul', sending: 'Se deschide clientul de e-mail…', direct: 'Contact direct', note: 'Sunt disponibil pentru proiecte de inginerie software, frontend și full-stack care implică aplicații web, sisteme e-commerce, API-uri și instrumente interne.', details: ['E-mail', 'LinkedIn'] },
    footer: { description: 'Inginer software din Brașov, România. Construiesc aplicații web fiabile, sisteme e-commerce și instrumente bazate pe date.', quick: 'Linkuri rapide', follow: 'Urmărește-mă', made: 'Creat cu', by: 'de Szakacs Barna', built: 'Construit cu React · Vite · Tailwind CSS · Framer Motion' },
  },
  hu: {
    language: { label: 'Nyelv', select: 'Válassz nyelvet' },
    nav: ['Kezdőlap', 'Rólam', 'Tapasztalat', 'Készségek', 'Projektek', 'Tanúsítványok', 'Kapcsolat'], navbar: { talk: 'Beszéljünk', menu: 'Menü váltása' },
    hero: { roles: ['Szoftvermérnök', 'Full-stack fejlesztő', 'Üzleti alkalmazásfejlesztő', 'React és Node.js fejlesztő', 'Frontend mérnök'], availability: 'Nyitott vagyok új lehetőségekre', greeting: 'Üdv, Barna vagyok', scroll: 'Görgess', tagline: 'A Brassói Transilvania Egyetem informatika és villamosmérnöki szakán végeztem. Karbantartható üzleti alkalmazásokat, reszponzív felületeket és operatív eszközöket építek, az adatokra, teljesítményre és gyakorlati munkafolyamatokra összpontosítva.', contact: 'Kapcsolat', work: 'Munkáim megtekintése' },
    about: { eyebrow: 'Rólam', title: 'Bemutatkozás', available: 'Munkára nyitott', paragraphs: ['A Brassói Transilvania Egyetem informatika és villamosmérnöki szakán végeztem Romániában. Három vállalatnál eltöltött öt év alatt e-kereskedelmi platformokat, belső üzleti eszközöket és teljesítményorientált webalkalmazásokat szállítottam.', 'Munkám része egy szerepköralapú belső operatív platform rendelés-, feladat-, naptár-, dokumentumkövetési, értesítési és jelentési munkafolyamatokkal. React, TypeScript, Node.js, Express, Supabase és Vercel segítségével termékkövetelményeket alakítok robusztus felületekké, API-kká, adatfolyamokká és karbantartható szoftverré.'], pills: ['Brassó, Románia', 'Informatika és villamosmérnöki', '4 nyelv'], languages: 'Nyelvek', languageLevels: [['Magyar', 'Anyanyelvi'], ['Román', 'Anyanyelvi'], ['Angol', 'B2 haladó'], ['Német', 'Alapfok']], stats: [['5+', 'Év tapasztalat'], ['3', 'Vállalat'], ['15+', 'Technológia']] },
    experience: { eyebrow: 'Szakmai út', title: 'Szakmai tapasztalat', fullTime: 'Teljes munkaidő', items: [{ role: 'Webfejlesztő és digitális növekedési szakértő', duration: '2025. jún. — jelenleg', summary: 'Az Ambisun digitális átalakulását vezettem erősebb online jelenlét, operatív eszközök és teljesítményorientált webes élmények megvalósításával a prémium pergola- és üvegrendszerek piacán.', achievements: ['Teljes weboldal-újratervezést valósítottam meg, beleértve az információs architektúrát, a szöveget és az UX-et, a márka- és konverziós célokhoz igazítva', 'Egyedi kapcsolatfelvételi és leadgeneráló űrlapokat fejlesztettem, amelyek új ügyfelek szerzését támogatták', 'A Core Web Vitals értékeket szkriptek szétválasztásával, feltételes betöltéssel és eszközoptimalizálással javítottam', 'Egyedi WordPress bővítményeket fejlesztettem belső és outlet munkafolyamatokhoz', 'React, Vite, Supabase és Vercel használatával teljes körű belső analitikai alkalmazást terveztem és telepítettem az értékesítés és működés követésére', 'Operatív adatokat modelleztem és jelentési munkafolyamatokat építettem megbízható termék- és értékesítési betekintésekhez', 'Műszaki, marketing- és gyártási csapatokkal dolgoztam együtt az üzleti igények használható megoldásokká alakításán'] }, { role: 'Frontend webfejlesztő', duration: '2022. szept. — 2025. ápr.', summary: 'Ügyfélközpontú e-kereskedelmi és webes projektekhez járultam hozzá, elsősorban Shopify Liquid témafejlesztésre, frontend teljesítményre és kifinomult, konverzióorientált felületekre összpontosítva.', achievements: ['Shopify Liquid témákat és e-kereskedelmi áruházakat építettem és testreszabtam ügyféligényekhez', 'Reszponzív, akadálymentes felületeket készítettem HTML5, CSS3 és Bootstrap használatával', 'Interaktív frontend funkciókat és dinamikus UI-komponenseket valósítottam meg JavaScript és jQuery segítségével', 'Harmadik féltől származó szolgáltatásokat és API-kat integráltam JSON alapú adatcserével', 'Git segítségével kezeltem a forráskódot és az együttműködési munkafolyamatokat', 'WordPress oldalakat fejlesztettem és tartottam karban, bővítve full-stack tapasztalatomat'] }, { role: 'Junior webfejlesztő', duration: '2020 — 2022', summary: 'Frontend és backend fejlesztési alapismereteket szereztem ügyfélprojekteken, miközben kiépítettem a mérnöki munkához szükséges fegyelmet.', achievements: ['Ügyfélweboldalakat fejlesztettem és tartottam karban frontend és backend rétegekben', 'Relációs adatbázisokat terveztem és kezeltem PHP és MySQL használatával', 'C és C++ nyelveket alkalmaztam rendszer- és beágyazott környezetekben'] }] },
    skills: { eyebrow: 'Amivel dolgozom', title: 'Készségek és technológiák', categories: ['Frontend', 'Shopify és e-kereskedelem', 'Backend és adatok', 'Mérnöki eszközök', 'Üzleti alkalmazások', 'Alkalmazásszállítás'] },
    projects: { eyebrow: 'Amit építettem', title: 'Projektek', live: 'Élő', demo: 'Élő bemutató', source: 'Forráskód', features: 'Fő funkciók', items: [{ subtitle: 'Belső operatív és üzletiintelligencia-platform', description: 'Az Ambisun számára végponttól végpontig épített full-stack belső platform, amely a széttagolt manuális követést összekapcsolt operatív munkafolyamatokkal váltja fel. A munkatársi és adminisztrátori nézetek egy rendszerben támogatják a rendelés-, feladat-, naptár-, dokumentum-, értesítés- és értékesítési jelentési folyamatokat.', features: ['Szerepköralapú munkatársi és adminisztrátori folyamatok a napi működéshez', 'Szerkeszthető rendelések, színkódolt feladatok, naptárütemezés és átütemezési folyamatok', 'Céges járműdokumentumok követése operatív értesítésekkel', 'KPI-jelentések értékesítéshez és lezárt rendelésekhez, termék- és rendeléselemzéssel'] }, { subtitle: 'EV intelligenciaplatform és hatótávkalkulátor', description: 'Teljesítményközpontú TypeScript alkalmazás egy gondozott elektromosjármű-adatbázis felfedezéséhez. A legújabb verzió 52 márka 149 elektromos járművét tartalmazza gyors szűréssel, részletes specifikációkkal, összehasonlításokkal, valamint a valós hatótáv és töltés tervezését támogató mérnöki eszközökkel.', features: ['149 elektromos jármű 52 márkától, részletes specifikációkkal és modellváltozatokkal', 'EV katalógus szűrése és böngészése márka, karosszéria, hatótáv, ár és akkumulátorkapacitás szerint', 'Legfeljebb három jármű összehasonlítása hatótáv, hatékonyság, akkumulátor és ár alapján', 'Valós hatótáv, energiafelhasználás és töltési megállók modellezése a kalkulátorral és az Engineering Labbal'] }] },
    certifications: { eyebrow: 'Eredmények', title: 'Tanúsítványok és képzés', links: ['Credly jelvény megtekintése', 'Tanúsítvány megtekintése'], items: [['Hálózati alapismeretek', 'A hálózatok, eszközkommunikáció, hálózati címzés és alapvető szolgáltatások alapjai.'], ['B2 szintű haladó angol nyelvvizsga', 'Cambridge által tanúsított B2 szintű angol nyelvtudás.'], ['Frontend fejlesztés', 'Teljes frontend tananyag: HTML, CSS, Bootstrap, JavaScript. Backend modul: PHP és MySQL.'], ['Szakdolgozati projekt — eVerse', 'Szakdolgozatként fejlesztett full-stack e-learning platform: online környezet jövőbeli villamosmérnökök számára tananyaggal, felhasználókezeléssel és interaktív tartalommal.']] },
    contact: { eyebrow: 'Kapcsolat', title: 'Lépj kapcsolatba velem', intro: 'Van egy projekted, ötleted vagy lehetőséged? Szívesen hallok róla, legyen szó gyors kérdésről vagy részletes leírásról.', name: 'Neved', email: 'E-mail-cím', message: 'Üzenet', namePlaceholder: 'Kovács János', emailPlaceholder: 'janos@pelda.hu', messagePlaceholder: 'Írj a projektedről vagy lehetőségről...', send: 'Üzenet küldése', sending: 'Az e-mail-kliens megnyitása…', direct: 'Közvetlen kapcsolat', note: 'Szoftvermérnöki, frontend és full-stack projekteket vállalok, webalkalmazásokkal, e-kereskedelmi rendszerekkel, API-kkal és belső eszközökkel kapcsolatban.', details: ['E-mail', 'LinkedIn'] },
    footer: { description: 'Brassói szoftvermérnök. Megbízható webalkalmazásokat, e-kereskedelmi rendszereket és adatalapú eszközöket építek.', quick: 'Gyorslinkek', follow: 'Kövess', made: 'Készítette', by: 'Szakacs Barna', built: 'React · Vite · Tailwind CSS · Framer Motion felhasználásával készült' },
  },
  de: {
    language: { label: 'Sprache', select: 'Sprache auswählen' },
    nav: ['Startseite', 'Über mich', 'Erfahrung', 'Kompetenzen', 'Projekte', 'Zertifikate', 'Kontakt'], navbar: { talk: 'Kontakt aufnehmen', menu: 'Menü umschalten' },
    hero: { roles: ['Softwareingenieur', 'Full-Stack-Entwickler', 'Business-Application-Entwickler', 'React- und Node.js-Entwickler', 'Frontend-Ingenieur'], availability: 'Offen für neue Möglichkeiten', greeting: 'Hallo, ich bin', scroll: 'Scrollen', tagline: 'Absolvent der Informatik und Elektrotechnik an der Transilvania-Universität Brașov. Ich entwickle wartbare Geschäftsanwendungen, responsive Oberflächen und operative Tools mit Fokus auf Daten, Performance und praktische Arbeitsabläufe.', contact: 'Kontakt aufnehmen', work: 'Meine Arbeit ansehen' },
    about: { eyebrow: 'Über mich', title: 'Über mich', available: 'Offen für Arbeit', paragraphs: ['Absolvent der Informatik und Elektrotechnik an der Transilvania-Universität Brașov, Rumänien. In fünf Jahren bei drei Unternehmen habe ich E-Commerce-Plattformen, interne Geschäftstools und leistungsorientierte Webanwendungen geliefert.', 'Meine Arbeit umfasst eine rollenbasierte interne Betriebsplattform mit Workflows für Aufträge, Aufgaben, Kalender, Dokumentenverfolgung, Benachrichtigungen und Reporting. Mit React, TypeScript, Node.js, Express, Supabase und Vercel überführe ich Produktanforderungen in robuste Oberflächen, APIs, Datenflüsse und wartbare Software.'], pills: ['Brașov, Rumänien', 'Informatik und Elektrotechnik', '4 Sprachen'], languages: 'Sprachen', languageLevels: [['Ungarisch', 'Muttersprache'], ['Rumänisch', 'Muttersprache'], ['Englisch', 'B2 Fortgeschritten'], ['Deutsch', 'Grundkenntnisse']], stats: [['5+', 'Jahre Erfahrung'], ['3', 'Unternehmen'], ['15+', 'Technologien']] },
    experience: { eyebrow: 'Beruflicher Werdegang', title: 'Berufserfahrung', fullTime: 'Vollzeit', items: [{ role: 'Webentwickler und Spezialist für digitales Wachstum', duration: 'Juni 2025 — heute', summary: 'Ich leitete die digitale Transformation von Ambisun durch eine stärkere Online-Präsenz, operative Tools und leistungsorientierte Web-Erlebnisse für den Markt hochwertiger Pergola- und Glassysteme.', achievements: ['Kompletten Website-Relaunch inklusive Informationsarchitektur, Texten und UX umgesetzt, abgestimmt auf Marken- und Conversion-Ziele', 'Individuelle Kontakt- und Leadgenerierungsformulare entwickelt, die die Gewinnung neuer Kunden unterstützten', 'Core Web Vitals durch Skripttrennung, bedingtes Laden und Asset-Optimierung verbessert', 'Individuelle WordPress-Plugins für Outlet- und interne Geschäftsprozesse entwickelt', 'Eine interne Full-Stack-Analyseanwendung mit React, Vite, Supabase und Vercel zur Verfolgung von Umsatz und Betrieb entwickelt und bereitgestellt', 'Betriebsdaten modelliert und Reporting-Workflows für verlässliche Einblicke in Produkt- und Vertriebsleistung aufgebaut', 'Mit Technik-, Marketing- und Produktionsteams zusammengearbeitet, um Geschäftsanforderungen in nutzbare Lösungen zu übersetzen'] }, { role: 'Frontend-Webentwickler', duration: 'Sept. 2022 — Apr. 2025', summary: 'Ich arbeitete an kundenorientierten E-Commerce- und Webprojekten mit Schwerpunkt auf Shopify-Liquid-Theme-Entwicklung, Frontend-Performance und ausgearbeiteten, conversion-orientierten Oberflächen.', achievements: ['Shopify-Liquid-Themes und E-Commerce-Shops nach Kundenanforderungen entwickelt und angepasst', 'Responsive und barrierearme Oberflächen mit HTML5, CSS3 und Bootstrap geliefert', 'Interaktive Frontend-Funktionen und dynamische UI-Komponenten mit JavaScript und jQuery umgesetzt', 'Drittanbieter-Dienste und APIs über JSON-basierten Datenaustausch integriert', 'Quellcode und kollaborative Arbeitsabläufe mit Git verwaltet', 'WordPress-Websites entwickelt und gepflegt, wodurch sich die Full-Stack-Erfahrung erweiterte'] }, { role: 'Junior-Webentwickler', duration: '2020 — 2022', summary: 'Grundlegende Erfahrung in Frontend- und Backend-Entwicklung auf Kundenprojekten gesammelt und dabei technische Disziplin aufgebaut.', achievements: ['Kundenwebsites in Frontend- und Backend-Schichten entwickelt und gepflegt', 'Relationale Datenbanken mit PHP und MySQL entworfen und verwaltet', 'C und C++ in systemnahen und Embedded-Kontexten eingesetzt'] }] },
    skills: { eyebrow: 'Womit ich arbeite', title: 'Kompetenzen und Technologien', categories: ['Frontend', 'Shopify und E-Commerce', 'Backend und Daten', 'Engineering-Werkzeuge', 'Geschäftsanwendungen', 'Anwendungsbereitstellung'] },
    projects: { eyebrow: 'Was ich entwickelt habe', title: 'Projekte', live: 'Live', demo: 'Live-Demo', source: 'Quellcode', features: 'Kernfunktionen', items: [{ subtitle: 'Interne Betriebs- und Business-Intelligence-Plattform', description: 'Eine von Grund auf entwickelte interne Full-Stack-Plattform für Ambisun, die fragmentierte manuelle Nachverfolgung durch verbundene Betriebsabläufe ersetzt. Rollenbasierte Ansichten für Mitarbeitende und Administratoren unterstützen Auftragsverwaltung, Aufgaben, Kalender, Dokumentennachverfolgung, Benachrichtigungen und Vertriebsreporting in einem System.', features: ['Rollenbasierte Workflows für Mitarbeitende und Administratoren im Tagesgeschäft', 'Bearbeitbare Aufträge, farbcodierte Aufgaben, Kalenderplanung und Umplanungsabläufe', 'Nachverfolgung von Fahrzeugdokumenten mit Benachrichtigungen für operative Aufgaben', 'KPI-Reporting für Vertrieb und abgeschlossene Aufträge mit Produkt- und Auftragsanalyse'] }, { subtitle: 'EV-Intelligenzplattform und Reichweitenrechner', description: 'Eine leistungsorientierte TypeScript-Anwendung zum Erkunden einer kuratierten EV-Datenbank. Die neueste Version umfasst 149 Elektrofahrzeuge von 52 Marken mit schneller Filterung, detaillierten Spezifikationen, Vergleichsabläufen und Engineering-Tools für realistische Reichweiten- und Ladeplanung.', features: ['149 Elektrofahrzeuge von 52 Marken mit detaillierten Spezifikationen und Modellvarianten', 'EV-Katalog nach Marke, Karosserieform, Reichweite, Preis und Batteriekapazität filtern und durchsuchen', 'Bis zu drei Fahrzeuge nach Reichweite, Effizienz, Batterie und Preisdaten vergleichen', 'Reale Reichweite, Energieverbrauch und Ladestopps mit Reichweitenrechner und Engineering Lab modellieren'] }] },
    certifications: { eyebrow: 'Erfolge', title: 'Zertifikate und Ausbildung', links: ['Credly-Abzeichen ansehen', 'Zertifikat ansehen'], items: [['Netzwerk-Grundlagen', 'Grundlagen von Netzwerken, Gerätekommunikation, Netzwerkadressierung und wesentlichen Diensten.'], ['B2-Zertifikat für fortgeschrittenes Englisch', 'Von Cambridge zertifizierte Englischkenntnisse auf B2-Niveau.'], ['Frontend-Entwicklung', 'Vollständiger Frontend-Lehrplan: HTML, CSS, Bootstrap, JavaScript. Backend-Modul: PHP und MySQL.'], ['Bachelorprojekt — eVerse', 'Als Bachelorarbeit entwickelte Full-Stack-E-Learning-Plattform: Online-Umgebung für künftige Elektroingenieure mit Lehrinhalten, Benutzerverwaltung und interaktiven Inhalten.']] },
    contact: { eyebrow: 'Kontakt', title: 'Kontaktieren Sie mich', intro: 'Haben Sie ein Projekt, eine Idee oder eine Gelegenheit? Ich freue mich, davon zu hören, egal ob es eine kurze Frage oder ein detailliertes Briefing ist.', name: 'Ihr Name', email: 'E-Mail-Adresse', message: 'Nachricht', namePlaceholder: 'Max Mustermann', emailPlaceholder: 'max@beispiel.de', messagePlaceholder: 'Erzählen Sie mir von Ihrem Projekt oder Ihrer Gelegenheit...', send: 'Nachricht senden', sending: 'E-Mail-Programm wird geöffnet…', direct: 'Direkter Kontakt', note: 'Ich bin für Software-Engineering-, Frontend- und Full-Stack-Projekte verfügbar, die Webanwendungen, E-Commerce-Systeme, APIs und interne Tools umfassen.', details: ['E-Mail', 'LinkedIn'] },
    footer: { description: 'Softwareingenieur aus Brașov, Rumänien. Ich entwickle zuverlässige Webanwendungen, E-Commerce-Systeme und datengestützte Tools.', quick: 'Schnelllinks', follow: 'Folgen Sie mir', made: 'Erstellt mit', by: 'von Szakacs Barna', built: 'Erstellt mit React · Vite · Tailwind CSS · Framer Motion' },
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('portfolio-language') || 'en')

  useEffect(() => {
    document.documentElement.lang = language
    localStorage.setItem('portfolio-language', language)
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}